%% X is a 2 x 1 vector
% Mu is 2 x 1 vector
% Sigma is 2 x 2 matrix
function [f] = gauss_2d(X, Mu, Sigma) 
    f = 1 / (2 * pi * ...
    abs(Sigma(1, 1) * Sigma(2, 2) - Sigma(2, 1) * Sigma(1, 2)) ^ (0.5)) * ...
    exp(-0.5 * (((X(1) - Mu(1)) ^ 2 * Sigma(1, 1) + ...
                2 * (X(2) - Mu(2)) * (X(1) - Mu(1)) * Sigma(2, 1) + ...
                (X(2) - Mu(2)) ^ 2 * Sigma(2, 2))));
            
            